//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comments
    {
        public int id { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public int article_id { get; set; }
        public bool is_show { get; set; }
        public string content { get; set; }
        public System.DateTime create_at { get; set; }
    
        public virtual article article { get; set; }
    }
}
